### ISSUE TITLE
Can you just make the app smaller =(((

### ISSUE THREAD

**Issue by niyakipham** [FireStreaker2/dotfiles#1]
![image](https://github.com/user-attachments/assets/c49e69f8-6a24-4c42-a041-c21c383e065e)

**Comment by FireStreaker2** [comment]
are you running it via xwayland or wayland?

**Comment by niyakipham** [comment]
> are you running it via xwayland or wayland?

i am running it through xwayland

**Comment by FireStreaker2** [comment]
xwayland causes some scaling issues, you can force chrome to run through wayland by adding these flags: ``--enable-features=UseOzonePlatform --ozone-platform=wayland`` (ex. ``google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland``

https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#force-apps-to-use-wayland

**Comment by niyakipham** [comment]
> xwayland causes some scaling issues, you can force chrome to run through wayland by adding these flags: `--enable-features=UseOzonePlatform --ozone-platform=wayland` (ex. `google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland`
> 
> https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#force-apps-to-use-wayland

I have found the solution

![image](https://github.com/user-attachments/assets/1e058b55-6b01-4152-8fae-00a848e149dc)
