### ISSUE TITLE
Add this spotify theme, dotsfile will be more amazing

### ISSUE THREAD

**Issue by niyakipham** [FireStreaker2/dotfiles#2]
![image](https://github.com/user-attachments/assets/8fa2fa48-7004-49e3-988b-fb7c512b35e7)

Please join me on discord

nickname: niyakipham

**Comment by FireStreaker2** [comment]
sorry, but since these are my personal dotfiles, i won't be adding themes/programs that i don't personally use

however, feel free to fork this repository and add your own edits !!
